# base image
FROM node:16 as build

# set env using default
# ARG env=staging

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN yarn install --silent
COPY . /app

# RUN cp .env.prod .env
RUN yarn build
RUN yarn global add serve
# RUN ls -al

CMD ["serve", "-s", "build", "-l","5000"]
